export const UI_DEV_TEST_MAIL = String(`<!DOCTYPE html>
<html>
<head>
<title>Bytes: Wasm 3.0 coming in hot</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="color-scheme" content="light dark">
<meta name="supported-color-schemes" content="light dark">
<link href="https://fonts.googleapis.com/css2?family=Fira+Mono&amp;family=Outfit:wght@400;500;700;900&amp;family=Paytone+One" rel="stylesheet">
<style>@media (prefers-color-scheme: dark) {
  .email-wrapper {
    color: #F9F4DA !important;
    background-color: #0F0D0E !important;
  }
  hr {
    border-color: #262422 !important;
  }
  mark {
    background-color: #231F20 !important;
    color: #F9F4DA !important;
  }
  pre {
    background-color: #231F20 !important;
    border: 1px solid #231F20 !important;
    color: #F9F4DA !important;
  }
  .bg-alt {
    background-color: #231F20 !important;
  }
  .unsubscribe-link {
    color: #504C48 !important;
  }
  .token.punctuation {
    color: #f9f4da !important;
  }
}
@media screen and (min-width: 600px) {
  .mobile-break {
    display: none;
  }
}</style>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
</head>
<body>
<table class="email-wrapper" border="0" cellspacing="0" width="100%" style="background-color: #FFF; border-collapse: collapse; color: #231F20; font-family: Outfit, sans-serif; font-size: 16px; width: 100%;"><tbody><tr>
<td style="border-collapse: collapse !important; word-break: normal;"></td>
<td width="600px" style="border-collapse: collapse !important; width: 600px; word-break: normal;"><div style="max-width:600px;padding-top:80px">
<div style="text-align:center"><img width="600" style="max-width: 100%; padding-bottom: 40px;" src="https://bytes.dev/images/bytes-banner-rounded.png" alt="Bytes"></div>
<p style="font-family: Outfit, sans-serif; font-size: 17px; line-height: 1.5; padding-left: 24px; padding-right: 24px;"><strong style="font-weight: 600;">Today’s issue:</strong> Why the Tesla app is 760 MB, Peter Thiel’s thoughts on signals, and new ways to get supply chain attacked.</p>
<p style="font-family: Outfit, sans-serif; font-size: 17px; line-height: 1.5; padding-left: 24px; padding-right: 24px;">Welcome to <a href="https://click.kit-mail6.com/v8u9gvmvq5frhvoevroswuv2edlllf9hq32o/x0hph3uewxzzdku5/aHR0cHM6Ly9ieXRlcy5kZXYvYXJjaGl2ZXMvNDI1" style="color: #12b5e5; font-weight: 600; text-decoration: underline;" url-id="1787652397">#425</a>.</p>
<hr style="border: 0; border-bottom: 5px solid; border-color: #f5f5f5; margin-bottom: 100px; margin-top: 100px;">
<div style="text-align:center;margin-bottom:36px">
<img width="80" src="https://bytes.dev/images/content/eyes.png" alt="Eyeballs logo" style="max-width: 100%;"><h2 style="font-family: Paytone One, sans-serif; font-size: 28px; margin-top: 10px; text-transform: uppercase;">The Main Thing</h2>
</div>
<div class="bg-alt" style="background-color: #f5f5f5; border-radius: 16px; margin-bottom: 40px; max-width: 100%; padding: 24px; padding-bottom: 12px;">
<img src="https://bytes.dev/images/content/pigeon-man.jpg" alt="A man with a pigeon's head" width="600" style="border-radius: 5px; max-width: 100%;"><p style="font-family: Outfit, sans-serif; font-size: 15px; font-style: italic; line-height: 1; margin: 0; padding-bottom: 4px; padding-left: 24px; padding-right: 24px; padding-top: 10px; text-align: center;">I built the app with Wasm, btw<!-- --> </p>
</div>
<h3 style="font-size: 24px; margin-bottom: 0; padding-left: 24px; padding-right: 24px;">Wasm 3.0 coming in hot</h3>
<p style="font-family: Outfit, sans-serif; font-size: 17px; line-height: 1.5; padding-left: 24px; padding-right: 24px;">They say that every man under 60 thinks about WebAssembly at least once a day. So I guess I shouldn’t have been surprised when my 13-year-old nephew texted me about the “absolutely stacked” <a href="https://click.kit-mail6.com/v8u9gvmvq5frhvoevroswuv2edlllf9hq32o/6qhehoul70ww6zbo/aHR0cHM6Ly93ZWJhc3NlbWJseS5vcmcvbmV3cy8yMDI1LTA5LTE3LXdhc20tMy4wLw==" style="color: #12b5e5; font-weight: 600; text-decoration: underline;" url-id="1787652398">Wasm 3.0</a> launch on Wednesday.</p>
<p style="font-family: Outfit, sans-serif; font-size: 17px; line-height: 1.5; padding-left: 24px; padding-right: 24px;">And he wasn’t wrong. This is arguably the project’s biggest release since dropping v1.0 <em>eight years ago</em>, when they first introduced the concept of a “portable compilation target” for allowing browsers and runtimes to run low-level languages like Rust and C++.</p>
<p style="font-family: Outfit, sans-serif; font-size: 17px; line-height: 1.5; padding-left: 24px; padding-right: 24px;">Let’s break down the biggest features:</p>
<ul>
<li>
<p style="font-family: Outfit, sans-serif; font-size: 17px; line-height: 1.5;"><strong style="font-weight: 600;">Memory64</strong> – The old 4GB memory ceiling is gone. Wasm modules can now theoretically address up to 16 exabytes. Browsers still cap at 16GB, but this is a massive unlock for game engines, ML workloads, edge compute, and other projects outside the web.</p>
</li>
<li>
<p style="font-family: Outfit, sans-serif; font-size: 17px; line-height: 1.5;"><strong style="font-weight: 600;">Multiple memories</strong> – Previously, each Wasm module lived in its own little fridge with its own jar of peanut butter. Now a single module can declare multiple memories and copy directly between them. That makes static linking less painful and opens up cleaner patterns for isolating private data or buffers.</p>
</li>
<li>
<p style="font-family: Outfit, sans-serif; font-size: 17px; line-height: 1.5;"><strong style="font-weight: 600;">Garbage collection + typed references</strong> – Higher-level languages like Java, Kotlin, and Dart can now target Wasm more directly thanks to a built-in low-level GC system and richer type system. That enables safer calls, more efficient layouts, and fewer runtime hacks, which is the plumbing you need to make many non-JS languages actually viable in Wasm-land.</p>
</li>
<li>
<p style="font-family: Outfit, sans-serif; font-size: 17px; line-height: 1.5;"><strong style="font-weight: 600;">Other goodies</strong> – Native exception handling finally provides a sane way to <code style="font-size: 14px;">try/catch</code> in Wasm, tail calls are big for functional language support, and JS string builtins let Wasm modules read and manipulate JavaScript strings directly, without awkward glue code.</p>
</li>
</ul>
<p style="font-family: Outfit, sans-serif; font-size: 17px; line-height: 1.5; padding-left: 24px; padding-right: 24px;"><strong style="font-weight: 600;">Bottom Line:</strong> WebAssembly 1.0 gave us the dream of running anything on the <em>web,</em> powering impressive web apps like Figma and Photoshop. Wasm 3.0 is the biggest leap since then – it continues to make the web faster <em>and</em> positions Wasm as a universal execution layer beyond the browser. At least that’s what my nephew’s friends think.</p>
<table width="100%" cellpadding="0" cellspacing="0" border="0" style="border-collapse: collapse; margin-top: 40px; text-align: center;"><tbody><tr><td style="border-collapse: collapse !important; padding-top: 12px; word-break: normal;">
<a href="https://click.kit-mail6.com/v8u9gvmvq5frhvoevroswuv2edlllf9hq32o/kkhmh2unl4ee2wil/aHR0cHM6Ly9mYWNlYm9vay5jb20vc2hhcmVyL3NoYXJlci5waHA_dT1odHRwcyUzQSUyRiUyRmJ5dGVzLmRldiUyRmFyY2hpdmVzJTJGNDI1" rel="noopener" style="color: #12b5e5; font-weight: 600; padding-left: 5px; text-decoration: none;" target="_blank" url-id="1787652399"><img alt="" style="display: inline-block; max-width: 100%; width: 32px;" width="25" src="https://bytes.dev/images/fb-share-icon.png"></a><a href="https://click.kit-mail6.com/v8u9gvmvq5frhvoevroswuv2edlllf9hq32o/58hvh8ugml00o2f6/aHR0cHM6Ly93d3cubGlua2VkaW4uY29tL3NoYXJpbmcvc2hhcmUtb2Zmc2l0ZS8_dXJsPWh0dHBzJTNBJTJGJTJGYnl0ZXMuZGV2JTJGYXJjaGl2ZXMlMkY0MjU=" rel="noopener" style="color: #12b5e5; font-weight: 600; padding-left: 5px; text-decoration: none;" target="_blank" url-id="1787652400"><img alt="" style="display: inline-block; max-width: 100%; width: 32px;" width="25" src="https://bytes.dev/images/li-share-icon.png"></a><a href="https://click.kit-mail6.com/v8u9gvmvq5frhvoevroswuv2edlllf9hq32o/25h2h9u32ngg0zc3/aHR0cHM6Ly90d2l0dGVyLmNvbS9pbnRlbnQvdHdlZXQvP3RleHQ9V2h5JTIwV2FzbSUyMDMuMCUyMGlzJTIwdGhlJTIwcHJvamVjdCUyN3MlMjBiaWdnZXN0JTIwcmVsZWFzZSUyMG9mJTIwdGhlJTIwbGFzdCUyMDglMjB5ZWFycyZ1cmw9aHR0cHMlM0ElMkYlMkZieXRlcy5kZXYlMkZhcmNoaXZlcyUyRjQyNQ==" rel="noopener" style="color: #12b5e5; font-weight: 600; padding-left: 5px; text-decoration: none;" target="_blank" url-id="1787652401"><img alt="" style="display: inline-block; max-width: 100%; width: 32px;" width="25" src="https://bytes.dev/images/tw-share-icon.png"></a><a href="https://click.kit-mail6.com/v8u9gvmvq5frhvoevroswuv2edlllf9hq32o/qvh8h8udrqvv2mtl/bWFpbHRvOj9ib2R5PVRob3VnaHQlMjB5b3UlMjdkJTIwbG92ZSUyMHRoaXMlMjB3ZWVrJTI3cyUyMEJ5dGVzJTBBLS0tJTBBV2h5JTIwV2FzbSUyMDMuMCUyMGlzJTIwdGhlJTIwcHJvamVjdCUyN3MlMjBiaWdnZXN0JTIwcmVsZWFzZSUyMG9mJTIwdGhlJTIwbGFzdCUyMDglMjB5ZWFycyUwQWh0dHBzJTNBJTJGJTJGYnl0ZXMuZGV2JTJGYXJjaGl2ZXMlMkY0MjUmc3ViamVjdD1Zb3UlMjBsaWtlJTIwY29ybmJyZWFkJTNG" rel="noopener" style="color: #12b5e5; font-weight: 600; padding-left: 5px; text-decoration: none;" target="_blank" url-id="1787652402"><img alt="" style="display: inline-block; max-width: 100%; width: 32px;" width="25" src="https://bytes.dev/images/em-share-icon.png"></a>
</td></tr></tbody></table>
<hr style="border: 0; border-bottom: 5px solid; border-color: #f5f5f5; margin-bottom: 100px; margin-top: 100px;">
<div style="text-align:center;margin-bottom:36px">
<img width="150" src="https://bytes.dev/images/content/coderabbit-logo.png" alt="CodeRabbit logo" style="max-width: 100%;"><h2 style="font-family: Paytone One, sans-serif; font-size: 28px; margin-top: 10px; text-transform: uppercase;"><span>Our Friends <br class="mobile-break">(With Benefits)</span></h2>
</div>
<div class="bg-alt" style="background-color: #f5f5f5; border-radius: 16px; margin-bottom: 40px; max-width: 100%; padding: 24px; padding-bottom: 12px;">
<img src="https://bytes.dev/images/content/avatar-teamwork.jpg" alt="Aang and Zuko touching fists together" width="600" style="border-radius: 5px; max-width: 100%;"><p style="font-family: Outfit, sans-serif; font-size: 15px; font-style: italic; line-height: 1; margin: 0; padding-bottom: 4px; padding-left: 24px; padding-right: 24px; padding-top: 10px; text-align: center;">CodeRabbit teaming up with Claude to write and fix all my code<!-- --> </p>
</div>
<h3 style="font-size: 24px; margin-bottom: 0; padding-left: 24px; padding-right: 24px;"><a href="https://click.kit-mail6.com/v8u9gvmvq5frhvoevroswuv2edlllf9hq32o/g3hnhwum3xnno4ur/aHR0cHM6Ly9jb2RlcmFiYml0LmxpbmsvYnl0ZXMtY2xp" style="color: #12b5e5; font-weight: 600; text-decoration: underline;" url-id="1787652403">CodeRabbit CLI just launched – and it’s free</a></h3>
<p style="font-family: Outfit, sans-serif; font-size: 17px; line-height: 1.5; padding-left: 24px; padding-right: 24px;">CLI-based coding agents like Claude Code and Codex are writing more code than ever – but who’s gonna <em>review</em> all that AI-generated code?</p>
<p style="font-family: Outfit, sans-serif; font-size: 17px; line-height: 1.5; padding-left: 24px; padding-right: 24px;">That’s where <a href="https://click.kit-mail6.com/v8u9gvmvq5frhvoevroswuv2edlllf9hq32o/g3hnhwum3xnno4ur/aHR0cHM6Ly9jb2RlcmFiYml0LmxpbmsvYnl0ZXMtY2xp" style="color: #12b5e5; font-weight: 600; text-decoration: underline;" url-id="1787652403">CodeRabbit CLI</a> comes in. It gives you senior-level code reviews directly in your terminal, so your CLI code generation can flow straight into automated validation:</p>
<ul>
<li>
<p style="font-family: Outfit, sans-serif; font-size: 17px; line-height: 1.5;">Enables pre-commit reviews of both staged <em>and</em> unstaged changes</p>
</li>
<li>
<p style="font-family: Outfit, sans-serif; font-size: 17px; line-height: 1.5;">Fits into your existing Git workflow by reviewing uncommitted changes, staged files, specific commits, or entire branches</p>
</li>
<li>
<p style="font-family: Outfit, sans-serif; font-size: 17px; line-height: 1.5;">Flags AI hallucinations, code smells, and perf problems, then provides one-click fixes in the command line</p>
</li>
</ul>
<p style="font-family: Outfit, sans-serif; font-size: 17px; line-height: 1.5; padding-left: 24px; padding-right: 24px;"><a href="https://click.kit-mail6.com/v8u9gvmvq5frhvoevroswuv2edlllf9hq32o/g3hnhwum3xnno4ur/aHR0cHM6Ly9jb2RlcmFiYml0LmxpbmsvYnl0ZXMtY2xp" style="color: #12b5e5; font-weight: 600; text-decoration: underline;" url-id="1787652403">Install CodeRabbit CLI for free</a> – and give yourself a quality gate for all the code that Claude, Codex, and Gemini write.</p>
<hr style="border: 0; border-bottom: 5px solid; border-color: #f5f5f5; margin-bottom: 100px; margin-top: 100px;">
<div style="text-align:center;margin-bottom:36px">
<img width="110" src="https://bytes.dev/images/content/spot-the-bug.png" alt="Spot the Bug logo" style="max-width: 100%;"><h2 style="font-family: Paytone One, sans-serif; font-size: 28px; margin-top: 10px; text-transform: uppercase;">Spot the Bug</h2>
<div class="section-presenter" style="margin-bottom:50px;margin-top:15px">
<h4 style="font-size: 19px; margin-bottom: 0; padding-left: 24px; padding-right: 24px;">Sponsored by <a href="https://click.kit-mail6.com/v8u9gvmvq5frhvoevroswuv2edlllf9hq32o/9qhzhdudpnxx35s9/aHR0cHM6Ly93d3cuYXVnbWVudGNvZGUuY29tL2Jsb2cvYW5ub3VuY2luZy1uZXctbWNwLWludGVncmF0aW9ucw==" style="color: #12b5e5; font-weight: 600; text-decoration: underline;" url-id="1787652404">Augment Code</a>
</h4>
<p style="font-family: Outfit, sans-serif; font-size: 16px; line-height: 1.5; margin-top: 5px; padding-left: 24px; padding-right: 24px;"><em>They just announced <a href="https://click.kit-mail6.com/v8u9gvmvq5frhvoevroswuv2edlllf9hq32o/9qhzhdudpnxx35s9/aHR0cHM6Ly93d3cuYXVnbWVudGNvZGUuY29tL2Jsb2cvYW5ub3VuY2luZy1uZXctbWNwLWludGVncmF0aW9ucw==" style="color: #12b5e5; font-weight: 600; text-decoration: underline;" url-id="1787652404">new MCP integrations</a> with Vercel, Render, Honeycomb, and Heroku, so you can easily connect your agents to them with one click.</em></p>
</div>
</div>
<pre class="language-js" style="background-color: #f9f9f9; border: 1px solid #f9f9f9; border-radius: 8px; color: #231F20; overflow: auto; padding: 24px;"><code class="language-js" style="font-size: 14px;"><span class="token keyword" style="color: #f38ba3; font-size: 14px;">const</span> products <span class="token operator" style="color: #12b5e5; font-size: 14px;">=</span> <span class="token punctuation" style="color: #231F20; font-size: 14px;">[</span>
  <span class="token punctuation" style="color: #231F20; font-size: 14px;">{</span> <span class="token literal-property property" style="color: #12b5e5; font-size: 14px;">name</span><span class="token operator" style="color: #12b5e5; font-size: 14px;">:</span> <span class="token string" style="color: #f99157; font-size: 14px;">"Shirt"</span><span class="token punctuation" style="color: #231F20; font-size: 14px;">,</span> <span class="token literal-property property" style="color: #12b5e5; font-size: 14px;">price</span><span class="token operator" style="color: #12b5e5; font-size: 14px;">:</span> <span class="token number" style="color: #fcba28; font-size: 14px;">20</span><span class="token punctuation" style="color: #231F20; font-size: 14px;">,</span> <span class="token literal-property property" style="color: #12b5e5; font-size: 14px;">discount</span><span class="token operator" style="color: #12b5e5; font-size: 14px;">:</span> <span class="token boolean" style="color: #9d7dce; font-size: 14px;">true</span> <span class="token punctuation" style="color: #231F20; font-size: 14px;">}</span><span class="token punctuation" style="color: #231F20; font-size: 14px;">,</span>
  <span class="token punctuation" style="color: #231F20; font-size: 14px;">{</span> <span class="token literal-property property" style="color: #12b5e5; font-size: 14px;">name</span><span class="token operator" style="color: #12b5e5; font-size: 14px;">:</span> <span class="token string" style="color: #f99157; font-size: 14px;">"Pants"</span><span class="token punctuation" style="color: #231F20; font-size: 14px;">,</span> <span class="token literal-property property" style="color: #12b5e5; font-size: 14px;">price</span><span class="token operator" style="color: #12b5e5; font-size: 14px;">:</span> <span class="token number" style="color: #fcba28; font-size: 14px;">50</span><span class="token punctuation" style="color: #231F20; font-size: 14px;">,</span> <span class="token literal-property property" style="color: #12b5e5; font-size: 14px;">discount</span><span class="token operator" style="color: #12b5e5; font-size: 14px;">:</span> <span class="token boolean" style="color: #9d7dce; font-size: 14px;">false</span> <span class="token punctuation" style="color: #231F20; font-size: 14px;">}</span><span class="token punctuation" style="color: #231F20; font-size: 14px;">,</span>
  <span class="token punctuation" style="color: #231F20; font-size: 14px;">{</span> <span class="token literal-property property" style="color: #12b5e5; font-size: 14px;">name</span><span class="token operator" style="color: #12b5e5; font-size: 14px;">:</span> <span class="token string" style="color: #f99157; font-size: 14px;">"Hat"</span><span class="token punctuation" style="color: #231F20; font-size: 14px;">,</span> <span class="token literal-property property" style="color: #12b5e5; font-size: 14px;">price</span><span class="token operator" style="color: #12b5e5; font-size: 14px;">:</span> <span class="token number" style="color: #fcba28; font-size: 14px;">15</span><span class="token punctuation" style="color: #231F20; font-size: 14px;">,</span> <span class="token literal-property property" style="color: #12b5e5; font-size: 14px;">discount</span><span class="token operator" style="color: #12b5e5; font-size: 14px;">:</span> <span class="token boolean" style="color: #9d7dce; font-size: 14px;">true</span> <span class="token punctuation" style="color: #231F20; font-size: 14px;">}</span><span class="token punctuation" style="color: #231F20; font-size: 14px;">,</span>
  <span class="token punctuation" style="color: #231F20; font-size: 14px;">{</span> <span class="token literal-property property" style="color: #12b5e5; font-size: 14px;">name</span><span class="token operator" style="color: #12b5e5; font-size: 14px;">:</span> <span class="token string" style="color: #f99157; font-size: 14px;">"Socks"</span><span class="token punctuation" style="color: #231F20; font-size: 14px;">,</span> <span class="token literal-property property" style="color: #12b5e5; font-size: 14px;">price</span><span class="token operator" style="color: #12b5e5; font-size: 14px;">:</span> <span class="token number" style="color: #fcba28; font-size: 14px;">5</span><span class="token punctuation" style="color: #231F20; font-size: 14px;">,</span> <span class="token literal-property property" style="color: #12b5e5; font-size: 14px;">discount</span><span class="token operator" style="color: #12b5e5; font-size: 14px;">:</span> <span class="token boolean" style="color: #9d7dce; font-size: 14px;">true</span> <span class="token punctuation" style="color: #231F20; font-size: 14px;">}</span><span class="token punctuation" style="color: #231F20; font-size: 14px;">,</span>
<span class="token punctuation" style="color: #231F20; font-size: 14px;">]</span><span class="token punctuation" style="color: #231F20; font-size: 14px;">;</span>

<span class="token keyword" style="color: #f38ba3; font-size: 14px;">const</span> discountThreshold <span class="token operator" style="color: #12b5e5; font-size: 14px;">=</span> <span class="token number" style="color: #fcba28; font-size: 14px;">30</span><span class="token punctuation" style="color: #231F20; font-size: 14px;">;</span>
<span class="token keyword" style="color: #f38ba3; font-size: 14px;">const</span> discountRate <span class="token operator" style="color: #12b5e5; font-size: 14px;">=</span> <span class="token number" style="color: #fcba28; font-size: 14px;">0.1</span><span class="token punctuation" style="color: #231F20; font-size: 14px;">;</span>

<span class="token keyword" style="color: #f38ba3; font-size: 14px;">const</span> totalCost <span class="token operator" style="color: #12b5e5; font-size: 14px;">=</span> products<span class="token punctuation" style="color: #231F20; font-size: 14px;">.</span><span class="token function" style="color: #9d7dce; font-size: 14px;">reduce</span><span class="token punctuation" style="color: #231F20; font-size: 14px;">(</span><span class="token punctuation" style="color: #231F20; font-size: 14px;">(</span><span class="token parameter" style="color: #f38ba3; font-size: 14px;">acc<span class="token punctuation" style="color: #231F20; font-size: 14px;">,</span> product</span><span class="token punctuation" style="color: #231F20; font-size: 14px;">)</span> <span class="token operator" style="color: #12b5e5; font-size: 14px;">=&gt;</span> <span class="token punctuation" style="color: #231F20; font-size: 14px;">{</span>
  <span class="token keyword" style="color: #f38ba3; font-size: 14px;">if</span> <span class="token punctuation" style="color: #231F20; font-size: 14px;">(</span>product<span class="token punctuation" style="color: #231F20; font-size: 14px;">.</span>discount<span class="token punctuation" style="color: #231F20; font-size: 14px;">)</span> <span class="token punctuation" style="color: #231F20; font-size: 14px;">{</span>
    <span class="token keyword" style="color: #f38ba3; font-size: 14px;">if</span> <span class="token punctuation" style="color: #231F20; font-size: 14px;">(</span>product<span class="token punctuation" style="color: #231F20; font-size: 14px;">.</span>price <span class="token operator" style="color: #12b5e5; font-size: 14px;">&gt;</span> discountThreshold<span class="token punctuation" style="color: #231F20; font-size: 14px;">)</span> <span class="token punctuation" style="color: #231F20; font-size: 14px;">{</span>
      acc <span class="token operator" style="color: #12b5e5; font-size: 14px;">+=</span> product<span class="token punctuation" style="color: #231F20; font-size: 14px;">.</span>price <span class="token operator" style="color: #12b5e5; font-size: 14px;">*</span> <span class="token punctuation" style="color: #231F20; font-size: 14px;">(</span><span class="token number" style="color: #fcba28; font-size: 14px;">1</span> <span class="token operator" style="color: #12b5e5; font-size: 14px;">-</span> discountRate<span class="token punctuation" style="color: #231F20; font-size: 14px;">)</span><span class="token punctuation" style="color: #231F20; font-size: 14px;">;</span>
    <span class="token punctuation" style="color: #231F20; font-size: 14px;">}</span> <span class="token keyword" style="color: #f38ba3; font-size: 14px;">else</span> <span class="token punctuation" style="color: #231F20; font-size: 14px;">{</span>
      acc <span class="token operator" style="color: #12b5e5; font-size: 14px;">+=</span> product<span class="token punctuation" style="color: #231F20; font-size: 14px;">.</span>price<span class="token punctuation" style="color: #231F20; font-size: 14px;">;</span>
    <span class="token punctuation" style="color: #231F20; font-size: 14px;">}</span>
  <span class="token punctuation" style="color: #231F20; font-size: 14px;">}</span> <span class="token keyword" style="color: #f38ba3; font-size: 14px;">else</span> <span class="token punctuation" style="color: #231F20; font-size: 14px;">{</span>
    acc <span class="token operator" style="color: #12b5e5; font-size: 14px;">+=</span> product<span class="token punctuation" style="color: #231F20; font-size: 14px;">.</span>price<span class="token punctuation" style="color: #231F20; font-size: 14px;">;</span>
  <span class="token punctuation" style="color: #231F20; font-size: 14px;">}</span>
<span class="token punctuation" style="color: #231F20; font-size: 14px;">}</span><span class="token punctuation" style="color: #231F20; font-size: 14px;">,</span> <span class="token number" style="color: #fcba28; font-size: 14px;">0</span><span class="token punctuation" style="color: #231F20; font-size: 14px;">)</span><span class="token punctuation" style="color: #231F20; font-size: 14px;">;</span>

console<span class="token punctuation" style="color: #231F20; font-size: 14px;">.</span><span class="token function" style="color: #9d7dce; font-size: 14px;">log</span><span class="token punctuation" style="color: #231F20; font-size: 14px;">(</span><span class="token template-string" style="font-size: 14px;"><span class="token template-punctuation string" style="color: #f99157; font-size: 14px;">\`</span><span class="token string" style="color: #f99157; font-size: 14px;">Total cost: </span><span class="token interpolation" style="color: #12b5e5; font-size: 14px;"><span class="token interpolation-punctuation punctuation" style="color: #231F20; font-size: 14px;">\${</span>totalCost<span class="token interpolation-punctuation punctuation" style="color: #231F20; font-size: 14px;">}</span></span><span class="token template-punctuation string" style="color: #f99157; font-size: 14px;">\`</span></span><span class="token punctuation" style="color: #231F20; font-size: 14px;">)</span><span class="token punctuation" style="color: #231F20; font-size: 14px;">;</span>
</code></pre>
<hr style="border: 0; border-bottom: 5px solid; border-color: #f5f5f5; margin-bottom: 100px; margin-top: 100px;">
<div style="text-align:center;margin-bottom:36px">
<img width="110" src="https://bytes.dev/images/content/cool-bits.png" alt="Cool Bits logo" style="max-width: 100%;"><h2 style="font-family: Paytone One, sans-serif; font-size: 28px; margin-top: 10px; text-transform: uppercase;">Cool Bits</h2>
</div>
<ol>
<li>
<p style="font-family: Outfit, sans-serif; font-size: 17px; line-height: 1.5;"><a href="https://click.kit-mail6.com/v8u9gvmvq5frhvoevroswuv2edlllf9hq32o/3ohphdu37vrr9khr/aHR0cHM6Ly9waGlzaHl1cmwuY29tLw==" style="color: #12b5e5; font-weight: 600; text-decoration: underline;" url-id="1787652405">phishyurl.com</a> is a URL <del>shortener</del> <em>longener</em> that can make any URL look like a malicious crypto/dating/gambling site. Great for teaching your favorite OSS maintainer about phishing or escalating your cold war with the IT department.</p>
</li>
<li>
<p style="font-family: Outfit, sans-serif; font-size: 17px; line-height: 1.5;"><a href="https://click.kit-mail6.com/v8u9gvmvq5frhvoevroswuv2edlllf9hq32o/n2hohquv3egg54u6/aHR0cHM6Ly9ibGF6aXR5LmNvbS90aGUtZXhwZXJ0LWd1aWRlLXRvLW5leHRqcy1wZXJmb3JtYW5jZS1vcHRpbWl6YXRpb24_dXRtX2NhbXBhaWduPWVib29rLWd1aWRlLW5leHQtanMtcGVyZm9ybWFuY2Utb3B0aW1pemF0aW9uJnV0bV9jb250ZW50PWJ5dGVzJnV0bV9tZWRpdW09ZW1haWwmdXRtX3NvdXJjZT1uZXdzbGV0dGVy" style="color: #12b5e5; font-weight: 600; text-decoration: underline;" url-id="1787652406">The Expert Guide to Next.js Performance Optimization 2025</a> is a free, 10-chapter ebook filled with real-life examples and open-source libraries to help you fix bottlenecks and boost performance in enterprise-scale Next.js apps. [sponsored]</p>
</li>
<li>
<p style="font-family: Outfit, sans-serif; font-size: 17px; line-height: 1.5;">The Angular team just open sourced <a href="https://click.kit-mail6.com/v8u9gvmvq5frhvoevroswuv2edlllf9hq32o/48hvh7umrk99qocx/aHR0cHM6Ly9ibG9nLmFuZ3VsYXIuZGV2L2JleW9uZC10aGUtaG9yaXpvbi1ob3ctYW5ndWxhci1pcy1lbWJyYWNpbmctYWktZm9yLW5leHQtZ2VuLWFwcHMtN2E3ZWQ3MDZlMWEz" style="color: #12b5e5; font-weight: 600; text-decoration: underline;" url-id="1787652407">Web Codegen Scorer</a> to help AI models generate better framework code. “Web Components solves this,” <em>he muttered to his stuffed animals in his parents’ spare bedroom.</em></p>
</li>
<li>
<p style="font-family: Outfit, sans-serif; font-size: 17px; line-height: 1.5;"><a href="https://click.kit-mail6.com/v8u9gvmvq5frhvoevroswuv2edlllf9hq32o/wnh2h6uqw84439h7/aHR0cHM6Ly9leHBvLmRldi9jaGFuZ2Vsb2cvc2RrLTU0" style="color: #12b5e5; font-weight: 600; text-decoration: underline;" url-id="1787652408">Expo SDK 54</a> comes with support for Liquid Glass icons, precompiled React Native for iOS, and more.</p>
</li>
<li>
<p style="font-family: Outfit, sans-serif; font-size: 17px; line-height: 1.5;">In related news, the Emerge Tools team broke down <a href="https://click.kit-mail6.com/v8u9gvmvq5frhvoevroswuv2edlllf9hq32o/reh8h9um0n77e2a2/aHR0cHM6Ly94LmNvbS9lbWVyZ2V0b29scy9zdGF0dXMvMTk2ODc1NDQyMjA4MDUyMDY5MQ==" style="color: #12b5e5; font-weight: 600; text-decoration: underline;" url-id="1787652409">why the Tesla iOS app is 760.3 MB</a> – aka 20% of the original iPhone’s storage capacity.</p>
</li>
<li>
<p style="font-family: Outfit, sans-serif; font-size: 17px; line-height: 1.5;">Blacksmith lets you run GitHub Actions <a href="https://click.kit-mail6.com/v8u9gvmvq5frhvoevroswuv2edlllf9hq32o/08hwhgu2dqxxk9tl/aHR0cHM6Ly93d3cuYmxhY2tzbWl0aC5zaC8=" style="color: #12b5e5; font-weight: 600; text-decoration: underline;" url-id="1787652410">2x faster than GitHub runners</a> and <em>*75% cheaper*</em>, because they run on bare metal gaming CPUs and optimize all your caching. It also makes your GitHub actions fully observable, so you can actually see when something goes wrong in your CI pipeline. [sponsored]</p>
</li>
<li>
<p style="font-family: Outfit, sans-serif; font-size: 17px; line-height: 1.5;">Matt Brophy wrote about how <a href="https://click.kit-mail6.com/v8u9gvmvq5frhvoevroswuv2edlllf9hq32o/8ghqh3uolk33x3fk/aHR0cHM6Ly9yZW1peC5ydW4vYmxvZy9taWRkbGV3YXJl" style="color: #12b5e5; font-weight: 600; text-decoration: underline;" url-id="1787652411">middleware is finally stable in React Router</a>.</p>
</li>
<li>
<p style="font-family: Outfit, sans-serif; font-size: 17px; line-height: 1.5;"><a href="https://click.kit-mail6.com/v8u9gvmvq5frhvoevroswuv2edlllf9hq32o/vqh3hmuop844d3tg/aHR0cHM6Ly9wbnBtLmlvL2Jsb2cvcmVsZWFzZXMvMTAuMTY=" style="color: #12b5e5; font-weight: 600; text-decoration: underline;" url-id="1787652412">pnpm 10.16</a> comes with a new security setting called <code style="font-size: 14px;">minimumReleaseAge</code> that specifies the number of minutes that must pass after a version is published before pnpm will install it. Because sometimes the difference between a hotfix and a supply-chain attack is about five minutes.</p>
</li>
<li>
<p style="font-family: Outfit, sans-serif; font-size: 17px; line-height: 1.5;">Vercel created <a href="https://click.kit-mail6.com/v8u9gvmvq5frhvoevroswuv2edlllf9hq32o/l2heh6ul3w44zzc6/aHR0cHM6Ly92ZXJjZWwuY29tL2Jsb2cvZ2VuZXJhdGUtc3RhdGljLWFpLXNkay10b29scy1mcm9tLW1jcC1zZXJ2ZXJzLXdpdGgtbWNwLXRvLWFpLXNkaw==" style="color: #12b5e5; font-weight: 600; text-decoration: underline;" url-id="1787652413"><code style="font-size: 14px;">mcp-to-ai-sdk</code></a>, a CLI that generates static AI SDK tool definitions from any MCP server to help address security and quality issues.</p>
</li>
<li>
<p style="font-family: Outfit, sans-serif; font-size: 17px; line-height: 1.5;">Minko Gechev gave a talk called <a href="https://click.kit-mail6.com/v8u9gvmvq5frhvoevroswuv2edlllf9hq32o/m2h7h6u38w997nhm/aHR0cHM6Ly9naXRuYXRpb24uY29tL2NvbnRlbnRzL3Jlc291cmNlZnVsLXN1c3BlbnNl" style="color: #12b5e5; font-weight: 600; text-decoration: underline;" url-id="1787652414">Resourceful Suspense</a> about using templating and signals to implement the suspense pattern in Angular. It’s kind of like the suspense I felt waiting for Peter Thiel to answer challenging interview questions like, “do you want humanity to survive?” and “are you the anti-Christ?”</p>
</li>
</ol>
<hr style="border: 0; border-bottom: 5px solid; border-color: #f5f5f5; margin-bottom: 100px; margin-top: 100px;">
<div style="text-align:center;margin-bottom:36px">
<img width="110" src="https://bytes.dev/images/content/spot-the-bug.png" alt="Spot the Bug logo" style="max-width: 100%;"><h2 style="font-family: Paytone One, sans-serif; font-size: 28px; margin-top: 10px; text-transform: uppercase;">Spot the Bug: Solution</h2>
<div class="section-presenter" style="margin-bottom:50px;margin-top:15px"><h4 style="font-size: 19px; margin-bottom: 0; padding-left: 24px; padding-right: 24px;">Sponsored by <a href="https://click.kit-mail6.com/v8u9gvmvq5frhvoevroswuv2edlllf9hq32o/9qhzhdudpnxx35s9/aHR0cHM6Ly93d3cuYXVnbWVudGNvZGUuY29tL2Jsb2cvYW5ub3VuY2luZy1uZXctbWNwLWludGVncmF0aW9ucw==" style="color: #12b5e5; font-weight: 600; text-decoration: underline;" url-id="1787652404">Augment Code</a>
</h4></div>
</div>
<p style="font-family: Outfit, sans-serif; font-size: 17px; line-height: 1.5; padding-left: 24px; padding-right: 24px;">Total cost is <code style="font-size: 14px;">undefined</code>. The reduce function is missing a return statement. The reduce function should return the accumulator after the iteration is complete.</p>
<pre class="language-js" style="background-color: #f9f9f9; border: 1px solid #f9f9f9; border-radius: 8px; color: #231F20; overflow: auto; padding: 24px;"><code class="language-js" style="font-size: 14px;"><span class="token keyword" style="color: #f38ba3; font-size: 14px;">const</span> products <span class="token operator" style="color: #12b5e5; font-size: 14px;">=</span> <span class="token punctuation" style="color: #231F20; font-size: 14px;">[</span>
  <span class="token punctuation" style="color: #231F20; font-size: 14px;">{</span> <span class="token literal-property property" style="color: #12b5e5; font-size: 14px;">name</span><span class="token operator" style="color: #12b5e5; font-size: 14px;">:</span> <span class="token string" style="color: #f99157; font-size: 14px;">"Shirt"</span><span class="token punctuation" style="color: #231F20; font-size: 14px;">,</span> <span class="token literal-property property" style="color: #12b5e5; font-size: 14px;">price</span><span class="token operator" style="color: #12b5e5; font-size: 14px;">:</span> <span class="token number" style="color: #fcba28; font-size: 14px;">20</span><span class="token punctuation" style="color: #231F20; font-size: 14px;">,</span> <span class="token literal-property property" style="color: #12b5e5; font-size: 14px;">discount</span><span class="token operator" style="color: #12b5e5; font-size: 14px;">:</span> <span class="token boolean" style="color: #9d7dce; font-size: 14px;">true</span> <span class="token punctuation" style="color: #231F20; font-size: 14px;">}</span><span class="token punctuation" style="color: #231F20; font-size: 14px;">,</span>
  <span class="token punctuation" style="color: #231F20; font-size: 14px;">{</span> <span class="token literal-property property" style="color: #12b5e5; font-size: 14px;">name</span><span class="token operator" style="color: #12b5e5; font-size: 14px;">:</span> <span class="token string" style="color: #f99157; font-size: 14px;">"Pants"</span><span class="token punctuation" style="color: #231F20; font-size: 14px;">,</span> <span class="token literal-property property" style="color: #12b5e5; font-size: 14px;">price</span><span class="token operator" style="color: #12b5e5; font-size: 14px;">:</span> <span class="token number" style="color: #fcba28; font-size: 14px;">50</span><span class="token punctuation" style="color: #231F20; font-size: 14px;">,</span> <span class="token literal-property property" style="color: #12b5e5; font-size: 14px;">discount</span><span class="token operator" style="color: #12b5e5; font-size: 14px;">:</span> <span class="token boolean" style="color: #9d7dce; font-size: 14px;">false</span> <span class="token punctuation" style="color: #231F20; font-size: 14px;">}</span><span class="token punctuation" style="color: #231F20; font-size: 14px;">,</span>
  <span class="token punctuation" style="color: #231F20; font-size: 14px;">{</span> <span class="token literal-property property" style="color: #12b5e5; font-size: 14px;">name</span><span class="token operator" style="color: #12b5e5; font-size: 14px;">:</span> <span class="token string" style="color: #f99157; font-size: 14px;">"Hat"</span><span class="token punctuation" style="color: #231F20; font-size: 14px;">,</span> <span class="token literal-property property" style="color: #12b5e5; font-size: 14px;">price</span><span class="token operator" style="color: #12b5e5; font-size: 14px;">:</span> <span class="token number" style="color: #fcba28; font-size: 14px;">15</span><span class="token punctuation" style="color: #231F20; font-size: 14px;">,</span> <span class="token literal-property property" style="color: #12b5e5; font-size: 14px;">discount</span><span class="token operator" style="color: #12b5e5; font-size: 14px;">:</span> <span class="token boolean" style="color: #9d7dce; font-size: 14px;">true</span> <span class="token punctuation" style="color: #231F20; font-size: 14px;">}</span><span class="token punctuation" style="color: #231F20; font-size: 14px;">,</span>
  <span class="token punctuation" style="color: #231F20; font-size: 14px;">{</span> <span class="token literal-property property" style="color: #12b5e5; font-size: 14px;">name</span><span class="token operator" style="color: #12b5e5; font-size: 14px;">:</span> <span class="token string" style="color: #f99157; font-size: 14px;">"Socks"</span><span class="token punctuation" style="color: #231F20; font-size: 14px;">,</span> <span class="token literal-property property" style="color: #12b5e5; font-size: 14px;">price</span><span class="token operator" style="color: #12b5e5; font-size: 14px;">:</span> <span class="token number" style="color: #fcba28; font-size: 14px;">5</span><span class="token punctuation" style="color: #231F20; font-size: 14px;">,</span> <span class="token literal-property property" style="color: #12b5e5; font-size: 14px;">discount</span><span class="token operator" style="color: #12b5e5; font-size: 14px;">:</span> <span class="token boolean" style="color: #9d7dce; font-size: 14px;">true</span> <span class="token punctuation" style="color: #231F20; font-size: 14px;">}</span><span class="token punctuation" style="color: #231F20; font-size: 14px;">,</span>
<span class="token punctuation" style="color: #231F20; font-size: 14px;">]</span><span class="token punctuation" style="color: #231F20; font-size: 14px;">;</span>

<span class="token keyword" style="color: #f38ba3; font-size: 14px;">const</span> discountThreshold <span class="token operator" style="color: #12b5e5; font-size: 14px;">=</span> <span class="token number" style="color: #fcba28; font-size: 14px;">30</span><span class="token punctuation" style="color: #231F20; font-size: 14px;">;</span>
<span class="token keyword" style="color: #f38ba3; font-size: 14px;">const</span> discountRate <span class="token operator" style="color: #12b5e5; font-size: 14px;">=</span> <span class="token number" style="color: #fcba28; font-size: 14px;">0.1</span><span class="token punctuation" style="color: #231F20; font-size: 14px;">;</span>

<span class="token keyword" style="color: #f38ba3; font-size: 14px;">const</span> totalCost <span class="token operator" style="color: #12b5e5; font-size: 14px;">=</span> products<span class="token punctuation" style="color: #231F20; font-size: 14px;">.</span><span class="token function" style="color: #9d7dce; font-size: 14px;">reduce</span><span class="token punctuation" style="color: #231F20; font-size: 14px;">(</span><span class="token punctuation" style="color: #231F20; font-size: 14px;">(</span><span class="token parameter" style="color: #f38ba3; font-size: 14px;">acc<span class="token punctuation" style="color: #231F20; font-size: 14px;">,</span> product</span><span class="token punctuation" style="color: #231F20; font-size: 14px;">)</span> <span class="token operator" style="color: #12b5e5; font-size: 14px;">=&gt;</span> <span class="token punctuation" style="color: #231F20; font-size: 14px;">{</span>
  <span class="token keyword" style="color: #f38ba3; font-size: 14px;">if</span> <span class="token punctuation" style="color: #231F20; font-size: 14px;">(</span>product<span class="token punctuation" style="color: #231F20; font-size: 14px;">.</span>discount<span class="token punctuation" style="color: #231F20; font-size: 14px;">)</span> <span class="token punctuation" style="color: #231F20; font-size: 14px;">{</span>
    <span class="token keyword" style="color: #f38ba3; font-size: 14px;">if</span> <span class="token punctuation" style="color: #231F20; font-size: 14px;">(</span>product<span class="token punctuation" style="color: #231F20; font-size: 14px;">.</span>price <span class="token operator" style="color: #12b5e5; font-size: 14px;">&gt;</span> discountThreshold<span class="token punctuation" style="color: #231F20; font-size: 14px;">)</span> <span class="token punctuation" style="color: #231F20; font-size: 14px;">{</span>
      acc <span class="token operator" style="color: #12b5e5; font-size: 14px;">+=</span> product<span class="token punctuation" style="color: #231F20; font-size: 14px;">.</span>price <span class="token operator" style="color: #12b5e5; font-size: 14px;">*</span> <span class="token punctuation" style="color: #231F20; font-size: 14px;">(</span><span class="token number" style="color: #fcba28; font-size: 14px;">1</span> <span class="token operator" style="color: #12b5e5; font-size: 14px;">-</span> discountRate<span class="token punctuation" style="color: #231F20; font-size: 14px;">)</span><span class="token punctuation" style="color: #231F20; font-size: 14px;">;</span>
    <span class="token punctuation" style="color: #231F20; font-size: 14px;">}</span> <span class="token keyword" style="color: #f38ba3; font-size: 14px;">else</span> <span class="token punctuation" style="color: #231F20; font-size: 14px;">{</span>
      acc <span class="token operator" style="color: #12b5e5; font-size: 14px;">+=</span> product<span class="token punctuation" style="color: #231F20; font-size: 14px;">.</span>price<span class="token punctuation" style="color: #231F20; font-size: 14px;">;</span>
    <span class="token punctuation" style="color: #231F20; font-size: 14px;">}</span>
  <span class="token punctuation" style="color: #231F20; font-size: 14px;">}</span> <span class="token keyword" style="color: #f38ba3; font-size: 14px;">else</span> <span class="token punctuation" style="color: #231F20; font-size: 14px;">{</span>
    acc <span class="token operator" style="color: #12b5e5; font-size: 14px;">+=</span> product<span class="token punctuation" style="color: #231F20; font-size: 14px;">.</span>price<span class="token punctuation" style="color: #231F20; font-size: 14px;">;</span>
  <span class="token punctuation" style="color: #231F20; font-size: 14px;">}</span>
  <span class="token keyword" style="color: #f38ba3; font-size: 14px;">return</span> acc<span class="token punctuation" style="color: #231F20; font-size: 14px;">;</span>
<span class="token punctuation" style="color: #231F20; font-size: 14px;">}</span><span class="token punctuation" style="color: #231F20; font-size: 14px;">,</span> <span class="token number" style="color: #fcba28; font-size: 14px;">0</span><span class="token punctuation" style="color: #231F20; font-size: 14px;">)</span><span class="token punctuation" style="color: #231F20; font-size: 14px;">;</span>

console<span class="token punctuation" style="color: #231F20; font-size: 14px;">.</span><span class="token function" style="color: #9d7dce; font-size: 14px;">log</span><span class="token punctuation" style="color: #231F20; font-size: 14px;">(</span><span class="token template-string" style="font-size: 14px;"><span class="token template-punctuation string" style="color: #f99157; font-size: 14px;">\`</span><span class="token string" style="color: #f99157; font-size: 14px;">Total cost: </span><span class="token interpolation" style="color: #12b5e5; font-size: 14px;"><span class="token interpolation-punctuation punctuation" style="color: #231F20; font-size: 14px;">\${</span>totalCost<span class="token interpolation-punctuation punctuation" style="color: #231F20; font-size: 14px;">}</span></span><span class="token template-punctuation string" style="color: #f99157; font-size: 14px;">\`</span></span><span class="token punctuation" style="color: #231F20; font-size: 14px;">)</span><span class="token punctuation" style="color: #231F20; font-size: 14px;">;</span>
</code></pre>
<div style="text-align:center;padding-bottom:80px;padding-top:80px">
<div class="bg-alt" style="background-color: #f5f5f5; border-radius: 16px; margin-bottom: 40px; padding: 24px;"><div style="margin-top:-40px">
<img src="https://bytes.dev/images/bytes-icon.png" alt="Bytes" width="55px" style="max-width: 100%; width: 55px;"><h5 style="font-size:18px;font-weight:400;margin-bottom:24px">Want us to say nice things <br> about your company?</h5>
<div style="margin-bottom:16px"><a style="background-color: #FCBA28; border: 1px solid #231F20; border-radius: 100px; color: #231F20; font-size: 14px; font-weight: 600; padding: 8px 14px; text-decoration: none;" href="https://click.kit-mail6.com/v8u9gvmvq5frhvoevroswuv2edlllf9hq32o/dphehmue0rkkmqum/aHR0cHM6Ly9ieXRlcy5kZXYvYWR2ZXJ0aXNl" url-id="1787652415">Sponsor Bytes</a></div>
<div style="margin-bottom:20px"><a style="color: #FCBA28; font-size: 14px; font-weight: 600; text-decoration: underline;" href="https://click.kit-mail6.com/v8u9gvmvq5frhvoevroswuv2edlllf9hq32o/e0hph0u705ee20t8/aHR0cHM6Ly9ieXRlcy5kZXYvc2hhcmU=" url-id="1787652416">or share it</a></div>
<p style="font-family: Outfit, sans-serif; font-size: 14px; line-height: 1.5; padding-left: 24px; padding-right: 24px;">Built with ❤️ by<!-- --> <a style="color: #ed203d; font-weight: 600; text-decoration: underline;" href="https://click.kit-mail6.com/v8u9gvmvq5frhvoevroswuv2edlllf9hq32o/7qh7h2u9o388m9fz/aHR0cHM6Ly91aS5kZXY=" url-id="1787652417">ui.dev</a></p>
</div></div>
<p style="font-family: Outfit, sans-serif; font-size: 14px; line-height: 1.5; opacity: 0.5; padding-left: 24px; padding-right: 24px;">50 W Broadway Ste 333 PMB 51647 Salt Lake City, Utah 84101</p>
<div style="font-family:Papyrus, cursive"><a class="unsubscribe-link" href="https://click.kit-mail6.com/v8u9gvmvq5frhvoevroswuv2edlllf9hq32o/owhkhwuwr5nn7guv/aHR0cHM6Ly9ieXRlcy5kZXYvdW5zdWJzY3JpYmU=" style="color: #9B9890;" url-id="1787652418">Unsubscribe from Bytes</a></div>
</div>
</div></td>
<td style="border-collapse: collapse !important; word-break: normal;"></td>
</tr></tbody></table>

<span style="display: none"><a href="https://unsubscribe.kit-mail6.com/v8u9gvmvq5frhvoevroswuv2edlllf9hq32o">Unsubscribe</a></span>
<!-- -->
<img src="https://open.kit-mail6.com/v8u9gvmvq5frhvoevroswuv2edlllf9hq32o" alt="">
</body>
</html>`)